a=2;
b=True;
c=False;
d="Chethan";
e=None;
f=complex(2,3);
print("The type is",type(a));
list1=[1,2,3];
print(list1);
tupple1={"apple","bananna"};
print(tupple1);
dict1{"Name":"Rocky","Since":1951,"Gangster":True;
